package nginxcore

type CoreModule struct {
	Directives struct {
		AbsoluteRedirect           bool   `json:"absolute_redirect"`
		Aio                        string `json:"aio"`
		AioWrite                   bool   `json:"aio_write"`
		Alias                      string `json:"alias"`
		AuthDelay                  string `json:"auth_delay"`
		ChunkedTransferEncoding    bool   `json:"chunked_transfer_encoding"`
		ClientBodyBufferSize       string `json:"client_body_buffer_size"`
		ClientBodyInFileOnly       bool   `json:"client_body_in_file_only"`
		ClientBodyInSingleBuffer   bool   `json:"client_body_in_single_buffer"`
		ClientBodyTempPath         string `json:"client_body_temp_path"`
		ClientBodyTimeout          string `json:"client_body_timeout"`
		ClientHeaderBufferSize     string `json:"client_header_buffer_size"`
		ClientHeaderTimeout        string `json:"client_header_timeout"`
		ClientMaxBodySize          string `json:"client_max_body_size"`
		ConnectionPoolSize         string `json:"connection_pool_size"`
		DefaultType                string `json:"default_type"`
		Directio                   bool   `json:"directio"`
		DirectioAlignment          string `json:"directio_alignment"`
		DisableSymlinks            string `json:"disable_symlinks"`
		ErrorPage                  string `json:"error_page"`
		Etag                       bool   `json:"etag"`
		Http                       bool   `json:"http"`
		IfModifiedSince            bool   `json:"if_modified_since"`
		IgnoreInvalidHeaders       string `json:"ignore_invalid_headers"`
		Internal                   bool   `json:"internal"`
		KeepaliveDisable           bool   `json:"keepalive_disable"`
		KeepaliveRequests          string `json:"keepalive_requests"`
		KeepaliveTime              string `json:"keepalive_time"`
		KeepaliveTimeout           string `json:"keepalive_timeout"`
		LargeClientHeaderBuffers   string `json:"large_client_header_buffers"`
		LimitExcept                string `json:"limit_except"`
		LimitRate                  string `json:"limit_rate"`
		LimitRateAfter             string `json:"limit_rate_after"`
		LingeringClose             bool   `json:"lingering_close"`
		LingeringTime              string `json:"lingering_time"`
		LingeringTimeout           string `json:"lingering_timeout"`
		Listen                     string `json:"listen"`
		Location                   string `json:"location"`
		LogNotFound                bool   `json:"log_not_found"`
		LogSubrequest              bool   `json:"log_subrequest"`
		MaxRanges                  string `json:"max_ranges"`
		MergeSlashes               bool   `json:"merge_slashes"`
		MsiePadding                bool   `json:"msie_padding"`
		MsieRefresh                bool   `json:"msie_refresh"`
		OpenFileCache              bool   `json:"open_file_cache"`
		OpenFileCacheErrors        bool   `json:"open_file_cache_errors"`
		OpenFileCacheMinUses       string `json:"open_file_cache_min_uses"`
		OpenFileCacheValid         string `json:"open_file_cache_valid"`
		OutputBuffers              string `json:"output_buffers"`
		PortInRedirect             bool   `json:"port_in_redirect"`
		PostponeOutput             string `json:"postpone_output"`
		ReadAhead                  string `json:"read_ahead"`
		RecursiveErrorPages        bool   `json:"recursive_error_pages"`
		RequestPoolSize            string `json:"request_pool_size"`
		ResetTimedoutConnection    bool   `json:"reset_timedout_connection"`
		Resolver                   string `json:"resolver"`
		ResolverTimeout            string `json:"resolver_timeout"`
		Root                       string `json:"root"`
		Satisfy                    string `json:"satisfy"`
		SendLowat                  string `json:"send_lowat"`
		SendTimeout                string `json:"send_timeout"`
		Sendfile                   bool   `json:"sendfile"`
		SendfileMaxChunk           string `json:"sendfile_max_chunk"`
		Server                     string `json:"server"`
		ServerName                 string `json:"server_name"`
		ServerNameInRedirect       bool   `json:"server_name_in_redirect"`
		ServerNamesHashBucketSize  string `json:"server_names_hash_bucket_size"`
		ServerNamesHashMaxSize     string `json:"server_names_hash_max_size"`
		ServerTokens               string `json:"server_tokens"`
		SubrequestOutputBufferSize string `json:"subrequest_output_buffer_size"`
		TcpNodelay                 bool   `json:"tcp_nodelay"`
		TcpNopush                  bool   `json:"tcp_nopush"`
		TryFiles                   string `json:"try_files"`
		Types                      string `json:"types"`
		TypesHashBucketSize        string `json:"types_hash_bucket_size"`
		TypesHashMaxSize           string `json:"types_hash_max_size"`
		UnderscoresInHeaders       string `json:"underscores_in_headers"`
		VariablesHashBucketSize    string `json:"variables_hash_bucket_size"`
		VariablesHashMaxSize       string `json:"variables_hash_max_size"`
	} `json:"directives"`
}
