openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API definition
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/v1:
    /files:
      get:
        summary: Returns a list of all files
        operationId: listFiles
        tags:
          - files
        responses:
          '200':
            description: A list of files
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/File'
      post:
        summary: Creates a new file
        operationId: createFile
        tags:
          - files
        requestBody:
          description: The file to create
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        responses:
          '201':
            description: The created file
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/File'
      put:
        summary: Updates a file
        operationId: updateFile
        tags:
          - files
        parameters:
          - name: fileId
            in: path
            description: The ID of the file to update
            required: true
            schema:
              type: string
        requestBody:
          description: The updated file
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        responses:
          '200':
            description: The updated file
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/File'
    